apiVersion: v1
kind: Service
metadata:
  name: {{ include "route-to-contour-httpproxy.fullname" . }}-controller-manager-metrics-service
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: route-to-contour-httpproxy
    app.kubernetes.io/part-of: route-to-contour-httpproxy
    control-plane: controller-manager
  {{- include "route-to-contour-httpproxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    control-plane: controller-manager
  {{- include "route-to-contour-httpproxy.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.metricsService.ports | toYaml | nindent 2 -}}